version: '3'

services:
  app-verificacion-pago:
    container_name: app-verificacion-pago
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Agrega aqu√≠ tus variables de entorno necesarias
      # - MERCANTIL_API_KEY=tu_clave
      # - MERCANTIL_MERCHANT_ID=tu_id
